language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: QaiiN77Z/rabxt+pej9XZIe/P/w63EvvmN9or5elYvnAwO6cRnM2/HQCrc6miVuyodKs+7UqP0M1W0twZlxJdym0le5IQOntrAh8TJMPxR68/zEqSvQKEOgX3zn/K6r/cBOqvlfngqHmynbVuE8tLqMPZyilB0JmHFXuF9vEbHs=
    app:
      master: thomas-api
