language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: c8+z6vKLTOb75BRk0W/BbLtohs5bDZq9radWWtgT9r2TWxsfoybCQha1Fkrl9l2YG6HxMO+A2HEd1qBpJvn8EqAW8HnwUV4xPKtfEz7YRvVgy8RqIiH4EvROalZwu6hyYXonZGrwhJEuL9xQetMHVbfnQV1Vsw0B5lxKXj8aRD8=
  app: thomas-api
  on:
    repo: mashio-metro/thomas-api-server
notifications:
  slack:
    secure: TmArPQVNfqP+Lehb7m56bjJSVhzE1wo1AJCzfyyCuRLKQNLcCjdSMDMPgFbJhDuTUfGSVruiId6OZfQkKaC/vIdtbi6Rgqog4e+JJN0WWoqq5kK13s4Owp7WHFNyc/3TffUwfQYmJ3N+BLuZnA6W14Q6NWDIl1jmjWH2upmBWJ8=
