language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: ExBBIarXkpxaHWrOFFzc3Cm9AEYr3ErsAqZ9mQwPjX9efopcsYZ1WV9Yt8zcuVbLrLiHgjPS3jqE4gKHOxOTu+4Vet9Ix/V+hOKGehy7A+tlsAvZydNXDFg80hi5yFBUNJDut+t4jfW5jKFKhLiS20KLlM4QW6Qy7Vj9ZPcSLxc=
  app:
    master: thomas-api
