language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: c8+z6vKLTOb75BRk0W/BbLtohs5bDZq9radWWtgT9r2TWxsfoybCQha1Fkrl9l2YG6HxMO+A2HEd1qBpJvn8EqAW8HnwUV4xPKtfEz7YRvVgy8RqIiH4EvROalZwu6hyYXonZGrwhJEuL9xQetMHVbfnQV1Vsw0B5lxKXj8aRD8=
  app: thomas-api
  on:
    repo: mashio-metro/thomas-api-server
