language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
deploy:
  provider: heroku
  app:
    master: thomas-api
  api_key:
    secure: H8UZLGRt7+xNBhmtchMzx88whWEaEEEx+F7UczKKTbvorAtRVrqj7Y14qzcSGmIXFD1FM9ITdoj/1ckEDhlvRGLz/yR+h3qlTPElpcSbttyjBtLV7X/YV1jsGMWKuXpXXB5LNBPneWe7xxtmnoTIneF9fb5SQH6qFEjeD78Iu/Q=

